import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { buildLinuxGameDesktopEntry } from "./linux-desktop-entry";

export const setLinuxAutoLaunch = async (options: {
  enabled: boolean;
  minimized: boolean;
  executable: string;
  home: string;
  environment?: NodeJS.ProcessEnv;
}) => {
  const env = options.environment ?? process.env;
  const config =
    env.XDG_CONFIG_HOME && path.posix.isAbsolute(env.XDG_CONFIG_HOME)
      ? env.XDG_CONFIG_HOME
      : path.join(options.home, ".config");
  const directory = path.join(config, "autostart");
  const destination = path.join(directory, "io.gamehub.launcher.desktop");
  const existing = await fs.promises
    .readFile(destination, "utf8")
    .catch((error) => {
      if (error.code === "ENOENT") return null;
      throw error;
    });
  if (existing && !/^X-GameHub-Managed=true$/m.test(existing))
    throw new Error(
      "An existing unowned GameHub autostart entry was preserved. Rename it before changing this setting."
    );
  await fs.promises.mkdir(directory, { recursive: true });
  const temporary = `${destination}.${crypto.randomUUID()}.tmp`;
  try {
    const entry = buildLinuxGameDesktopEntry({
      name: "GameHub",
      executable: options.executable,
      args: options.minimized ? ["--hidden"] : [],
    });
    await fs.promises.writeFile(
      temporary,
      `${entry}Hidden=${!options.enabled}\n`,
      { flag: "wx", mode: 0o644 }
    );
    await fs.promises.rename(temporary, destination);
  } finally {
    await fs.promises.rm(temporary, { force: true });
  }

  // Migrate only the exact entry generated by our old auto-launch dependency.
  // Retain it under a non-.desktop suffix instead of deleting user metadata.
  for (const legacyDirectory of new Set([
    directory,
    path.join(options.home, ".config", "autostart"),
  ])) {
    const legacy = path.join(legacyDirectory, "GameHub.desktop");
    const content = await fs.promises.readFile(legacy, "utf8").catch(() => "");
    if (
      /^Name=GameHub$/m.test(content) &&
      /^Comment=GameHubstartup script$/m.test(content)
    ) {
      await fs.promises.rename(
        legacy,
        `${legacy}.migrated-${crypto.randomUUID()}`
      );
    }
  }
  return destination;
};
