import fs from "node:fs";
import path from "node:path";
import type {
  ControllerProfile,
  ControllerProfileStore,
  EmulatorBinary,
  EmulatorSystem,
} from "@types";
import { KNOWN_BINARIES } from "./known-binaries";
import { getEmulatorConfig } from "./emulators-repository";
import { cemuDataDir } from "./emulator-portable";
import { logger } from "../logger";
import {
  writeRalibretro,
  pcsx2PadSection,
  rpcs3Yaml,
  dolphinGcPadSection,
  dolphinWiimoteSection,
  cemuControllerXml,
  azaharControls,
  edenControls,
} from "./controller-writers";

export * from "./controller-writers";

/**
 * Apply a controller profile into each emulator's native config. Emulators
 * installed by GameHub live in `userData/emulators/<binary>/`; we write their
 * configs in PORTABLE mode (relative to the exe) so everything stays inside the
 * managed install and we don't fight per-user AppData paths. The section text is
 * generated by the verified writers; here we place/merge the files + set the
 * portable markers each emulator needs.
 */

const write = (file: string, content: string) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
};

/** Replace (or append) a `[Section]` block in an INI string. */
function replaceIniSection(ini: string, section: string, body: string): string {
  const header = `[${section}]`;
  const lines = ini.split(/\r?\n/);
  const start = lines.findIndex((l) => l.trim() === header);
  if (start === -1) {
    return (ini.trimEnd() + "\n\n" + body + "\n").trimStart();
  }
  let end = start + 1;
  while (end < lines.length && !/^\[.+\]\s*$/.test(lines[end])) end++;
  return [...lines.slice(0, start), body, "", ...lines.slice(end)]
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

function writeForBinary(
  binary: EmulatorBinary,
  installDir: string,
  profile: ControllerProfile,
  type: ControllerProfileStore["types"][EmulatorBinary]
): boolean {
  try {
    switch (binary) {
      case "ralibretro":
        return writeRalibretro(installDir, profile);

      case "pcsx2": {
        // Portable: <exe>/portable.ini triggers <exe>/inis/PCSX2.ini.
        write(path.join(installDir, "portable.ini"), "");
        const iniFile = path.join(installDir, "inis", "PCSX2.ini");
        const existing = fs.existsSync(iniFile)
          ? fs.readFileSync(iniFile, "utf-8")
          : "";
        write(
          iniFile,
          replaceIniSection(existing, "Pad1", pcsx2PadSection(profile))
        );
        return true;
      }

      case "rpcs3": {
        write(
          path.join(
            installDir,
            "config",
            "input_configs",
            "global",
            "Default.yml"
          ),
          rpcs3Yaml(profile)
        );
        return true;
      }

      case "dolphin": {
        // Portable: <exe>/portable.txt → <exe>/User.
        write(path.join(installDir, "portable.txt"), "");
        const cfgDir = path.join(installDir, "User", "Config");
        const gc = path.join(cfgDir, "GCPadNew.ini");
        const gcExisting = fs.existsSync(gc)
          ? fs.readFileSync(gc, "utf-8")
          : "";
        write(
          gc,
          replaceIniSection(gcExisting, "GCPad1", dolphinGcPadSection(profile))
        );
        const wm = path.join(cfgDir, "WiimoteNew.ini");
        const wmExisting = fs.existsSync(wm)
          ? fs.readFileSync(wm, "utf-8")
          : "";
        write(
          wm,
          replaceIniSection(
            wmExisting,
            "Wiimote1",
            dolphinWiimoteSection(profile)
          )
        );
        return true;
      }

      case "cemu": {
        const t =
          type && type.startsWith("wiiu") ? type : ("wiiu_gamepad" as const);
        write(
          path.join(
            cemuDataDir(installDir),
            "controllerProfiles",
            "controller0.xml"
          ),
          cemuControllerXml(
            profile,
            t as "wiiu_gamepad" | "wiiu_pro" | "wiiu_classic"
          )
        );
        return true;
      }

      case "azahar": {
        // Portable Citra/Azahar: a `user/` folder next to the exe.
        const iniFile = path.join(
          installDir,
          "user",
          "config",
          "qt-config.ini"
        );
        const existing = fs.existsSync(iniFile)
          ? fs.readFileSync(iniFile, "utf-8")
          : "";
        write(
          iniFile,
          replaceIniSection(existing, "Controls", azaharControls(profile))
        );
        return true;
      }

      case "eden": {
        // Portable Eden (Yuzu/Sudachi derivative): portable.txt → config/
        const iniFile = path.join(installDir, "config", "qt-config.ini");
        const existing = fs.existsSync(iniFile)
          ? fs.readFileSync(iniFile, "utf-8")
          : "";
        write(
          iniFile,
          replaceIniSection(existing, "Controls", edenControls(profile))
        );
        return true;
      }

      default:
        return false;
    }
  } catch (err) {
    logger.error(`[controller] write failed for ${binary}`, err);
    return false;
  }
}

/**
 * Re-apply every emulator's SAVED profile to its native config. Called at app
 * startup so a controller set up in a previous session survives a restart (and
 * survives the emulator being reinstalled/updated, which can reset its config).
 * Each installed emulator uses its own per-binary profile; `global` is only a
 * legacy seed for binaries the user never customised. RALibretro backs six
 * systems from one install, so mapping it once covers PS1/PSP/GBA/N64/DS/DSi.
 */
export async function reapplyAllControllerProfiles(
  store: ControllerProfileStore
): Promise<{ binary: EmulatorBinary; ok: boolean }[]> {
  const results: { binary: EmulatorBinary; ok: boolean }[] = [];
  const seen = new Set<EmulatorBinary>();

  for (const system of Object.keys(KNOWN_BINARIES) as EmulatorSystem[]) {
    const known = KNOWN_BINARIES[system];
    if (seen.has(known.binary)) continue;

    const config = await getEmulatorConfig(system);
    if (!config.executablePath || !fs.existsSync(config.executablePath))
      continue;

    // Only write configs the user actually customised — don't stamp a default
    // profile over an emulator the user hasn't touched here.
    const profile = store.byBinary[known.binary];
    if (!profile) continue;

    seen.add(known.binary);
    const ok = writeForBinary(
      known.binary,
      path.dirname(config.executablePath),
      profile,
      store.types[known.binary]
    );
    results.push({ binary: known.binary, ok });
  }

  return results;
}

/** Apply a single profile to just one emulator binary (per-console save). */
export async function applyControllerToBinary(
  binary: EmulatorBinary,
  profile: ControllerProfile,
  type: ControllerProfileStore["types"][EmulatorBinary]
): Promise<boolean> {
  for (const system of Object.keys(KNOWN_BINARIES) as EmulatorSystem[]) {
    if (KNOWN_BINARIES[system].binary !== binary) continue;
    const config = await getEmulatorConfig(system);
    if (config.executablePath && fs.existsSync(config.executablePath)) {
      return writeForBinary(
        binary,
        path.dirname(config.executablePath),
        profile,
        type
      );
    }
  }
  return false;
}
